//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace сорт
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class POBEDA_BDEntities : DbContext
    {
        private static POBEDA_BDEntities _context;

        public static POBEDA_BDEntities GetContext()
        {
            if (_context == null)
            {
                _context = new POBEDA_BDEntities();
            }

            return _context;
        }

        public POBEDA_BDEntities()
            : base("name=POBEDA_BDEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ArrayBD> ArrayBD { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
